word_list = {
    "Animais":[
        "aranha",
        "cão",
        "gato",
        "cavalo",
        "vaca",
        "coelho",
        "porco",
        "galinha",
        "galo",
        "ovelha",
        "borboleta",
        "abelha",
        "formiga",
        "pássaro",
        "morcego",
        "sapo",
        "rã",
        "tartaruga",
        "iguana",
        "crocodilo",
        "jacaré",
        "lagarto",
        "serpente",
        "cobra",
        "escorpião",
        "falcão",
        "golfinho",
        "baleia",
        "tubarão",
        "peixe",
        "caranguejo",
        "camarão",
        "lula",
        "polvo",
        "estrela-do-mar",
        "ouriço-do-mar",
        "coral",
        "chita",
        "abutre",
        "águia",
        "coruja",
        "andorinha",
        "pomba",
        "papagaio",
        "canário",
        "cisne",
        "pato",
        "ganso",
        "leão",
        "tigre",
        "elefante",
        "girafa",
        "rinoceronte",
        "hipopótamo",
        "zebra",
        "macaco",
        "gorila",
        "chimpanzé"
    ],
    "Cidades portuguesas":[
        "Lisboa",
        "Porto",
        "Coimbra",
        "Braga",
        "Aveiro",
        "Setúbal",
        "Vila Nova de Gaia",
        "Faro",
        "Leiria",
        "Évora",
        "Funchal",
        "Viana do Castelo",
        "Portimão",
        "Amadora",
        "Covilhã",
        "Santarém",
        "Paços de Ferreira",
        "Vila Real",
        "Barcelos",
        "Guarda",
        "Tomar",
        "Santa Maria da Feira",
        "Maia",
        "Gondomar",
        "Beja",
        "Cascais",
        "Matosinhos",
        "Oeiras",
        "Albufeira",
        "Porto Moniz",
        "Praia da Vitória",
        "Penafiel",
        "Santo Tirso",
        "Marinha Grande",
        "Pombal",
        "Torres Vedras",
        "Funchal",
        "Sintra",
        "Alcochete",
        "Almeida",
        "Viseu",
        "Vila Nova de Famalicão",
        "Chaves",
        "Praia da Graciosa"
    ],
    "Países":[
        "Equador",
        "Índia",
        "Grécia",
        "Lituânia",
        "Gâmbia",
        "Cazaquistão",
        "Nigéria",
        "Camarões",
        "Indonésia",
        "Portugal",
        "Alemanha",
        "Japão",
        "Irão",
        "República Democrática do Congo",
        "Países Baixos",
        "Senegal",
        "Bolívia",
        "Tailândia",
        "Egito",
        "Argélia",
        "Austrália",
        "Uruguai",
        "Macedónia do Norte",
        "Emirados Árabes Unidos",
        "Bélgica",
        "Mali",
        "Filipinas",
        "Argentina",
        "Suíça",
        "Tanzânia",
        "Ucrânia",
        "México",
        "Quênia",
        "Coreia do Sul",
        "Zâmbia",
        "Arábia Saudita",
        "Costa Rica",
        "Canadá",
        "Peru"]}